### ISSUE TITLE
High ping issue

### ISSUE THREAD

**Issue by jxian725** [vetid/otcv3#2]
the hack seems like having ping bug. The game is not laggy, just the displayed ping is somehow very high, and people able to identify you're hacking by watching your ping.

**Comment by vetid** [comment]
I have no idea, it could be just your internet.
For future support, ask here: https://discord.gg/tUJsJgX

**Comment by jxian725** [comment]
> I have no idea, it could be just your internet.
> For future support, ask here: https://discord.gg/tUJsJgX

Thank you! I just realize the high ping is caused by the Extended Backtracking.
